apiVersion: stellar.org/v1alpha1
kind: StellarNode
metadata:
  name: validator-suspended-example
  namespace: stellar
spec:
  nodeType: Validator
  network: Testnet
  version: "v21.0.0"

  # Suspend the validator - scales to 0 replicas but keeps Service active
  suspended: true

  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "4"
      memory: "16Gi"

  storage:
    storageClass: "standard"
    size: "100Gi"
    retentionPolicy: Retain

  validatorConfig:
    seedSecretRef: "validator-seed"
    enableHistoryArchive: true
    historyArchiveUrls:
      - "https://history.stellar.org/prd/core-testnet/core_testnet_001"

---
# Expected behavior when suspended:
#
# 1. StatefulSet scales to 0 replicas cleanly
# 2. Service remains active for peer discovery
# 3. PVC is retained (not deleted)
# 4. Status shows:
#    phase: Suspended
#    message: "Node suspended - scaled to 0 replicas"
#    conditions:
#      - type: Ready
#        status: "False"
#        reason: NodeSuspended
#        message: "Node is offline - replicas scaled to 0. Service remains active for peer discovery."
#
# 5. StatefulSet has annotations:
#    stellar.org/suspended: "true"
#    stellar.org/suspended-at: "<timestamp>"
#
# To resume the validator, simply set suspended: false and reapply
